services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://${PLEX_HOST}:32400/
    volumes:
      - /opt/plex/database:/config
      - /opt/plex/transcode:/transcode
      - /mnt/blockstore/plex/media:/data
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/dri:/dev/dri